### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by allensell** [seldonsmule/logmsg#1]
Eric,

I actually really have been meaning to tell you that after working with the other logging solution that I might like our old version better if it can work on top of the base logger and if you would just add a license to your version.  

I can add the license file for you if you would like.  A simple MIT license file would be great :)

**Comment by seldonsmule** [comment]
Sounds good.  We are in Mexico - but I can still access.  Did not really know what to do from a license standpoint - if you have a recommendation - that would be awesome.

Agree on having it work on top of base logger.  I had noticed other doing that.  I also liked how some have made plugins to post to common centralized log repositories.
